_wandb:
    value:
        cli_version: 0.23.0
        e:
            tsyy3iuudedlql41qpwo062w15rr3wij:
                args:
                    - -dataset
                    - cifar100
                    - --pfl_algo
                    - al
                    - --kd_data_fraction
                    - "1"
                    - --net
                    - resnet18_pretrain_fix_adapter
                    - --personalized
                    - --log_online
                    - --project
                    - pfl-cifar10
                    - --lmbda
                    - "1.0"
                    - --batch_size
                    - "16"
                    - --num_clients
                    - "20"
                    - --dirichlet_alpha
                    - "0.1"
                    - --clients-per-round
                    - "8"
                    - --num-rounds
                    - "200"
                    - -lr
                    - "0.001"
                    - --lr-decay
                    - "1"
                    - --decay-lr-every
                    - "50"
                    - --num_epochs
                    - "10"
                    - --aggregation
                    - kd
                    - --kd_dataset
                    - cifar100
                    - --kd_lr
                    - "0.001"
                    - --total_n_server_pseudo_batches
                    - "500"
                    - --early_stopping_server_batches
                    - "1000"
                    - --kd_eval_batches_freq
                    - "1"
                    - --kd_max_round
                    - "30"
                    - --kd_batch_size
                    - "2048"
                    - --output_summary_file
                    - outputs/cifar10/resnet18_pretrain_fix_adapter_al_bs16lr0.001_kd_cifar100kdbs2048lr0.001b500datafrac1max30_ncli20per8_lep10_a0.1_lmbda1.0
                    - --al_algo
                    - PGD
                codePath: run.py
                codePathLocal: run.py
                cpu_count: 192
                cpu_count_logical: 192
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "7528923684864"
                        used: "4552265711616"
                email: danny0628@naver.com
                executable: /home/project/anaconda3/envs/heart-pfl/bin/python
                git:
                    commit: df0c0a9fa39c3191aeec15c1c8ea76d818395be1
                    remote: https://github.com/danny0628/WACV_2026.git
                gpu: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-bb7d77cd-dcce-a726-1d51-bf03d422e687
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-381197c0-f7e6-8e25-6317-0e7aec4da300
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-7e3116a8-3c40-a8ad-252a-9a1e8b14e18c
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-c01a05cd-057a-b1fe-f8a3-48267e866522
                host: aigpu0914
                memory:
                    total: "811219558400"
                os: Linux-6.8.0-84-generic-x86_64-with-glibc2.17
                program: run.py
                python: CPython 3.8.20
                root: /home/mjkim/WACV_2026
                startedAt: "2025-11-20T01:47:55.361009Z"
                writerId: tsyy3iuudedlql41qpwo062w15rr3wij
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 51
            "2":
                - 1
                - 41
                - 51
            "3":
                - 13
            "4": 3.8.20
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
adapter_dropout:
    value: 0.3
aggregation:
    value: kd
al_algo:
    value: PGD
batch_size:
    value: 16
clients_per_round:
    value: 8
dataset:
    value: cifar100
decay_lr_every:
    value: 50
dirichlet_alpha:
    value: 0.1
early_stopping_server_batches:
    value: 1000
eval_every:
    value: 2
img_resolution:
    value: null
kd_KL_temperature:
    value: 1
kd_batch_size:
    value: 2048
kd_data_fraction:
    value: 1
kd_dataset:
    value: cifar100
kd_eval_batches_freq:
    value: 1
kd_lr:
    value: 0.001
kd_max_round:
    value: 30
kd_weight_decay:
    value: 0.0001
lmbda:
    value: 1
load_checkpoint:
    value: null
local_finetune:
    value: false
log_online:
    value: true
lr:
    value: 0.001
lr_decay:
    value: 1
model:
    value: resnet18
net:
    value: resnet18_pretrain_fix_adapter
nologging:
    value: false
num_clients:
    value: 20
num_epochs:
    value: 10
num_rounds:
    value: 200
output_summary_file:
    value: outputs/cifar10/resnet18_pretrain_fix_adapter_al_bs16lr0.001_kd_cifar100kdbs2048lr0.001b500datafrac1max30_ncli20per8_lep10_a0.1_lmbda1.0
patience_iter:
    value: 20
personalized:
    value: true
pfl_algo:
    value: al
project:
    value: pfl-cifar10
seed:
    value: 1
shard_per_user:
    value: null
start_finetune_rounds:
    value: 10000
test_batch_size:
    value: 2048
total_n_server_pseudo_batches:
    value: 500
validation:
    value: false
wandb_key:
    value: 16a6328223cc5e0c29a24c22c650fe2c1254823f
